apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: guestbook
  namespace: gke-fleet
spec:
  subscriptions:
  - image:
      repoURL: us-east4-docker.pkg.dev/sap-ems-gap-sandbox/ghcr/icarusdes/guestbook
      imageSelectionStrategy: SemVer
